//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.27 at 03:47:31 PM WET 
//


package eu.scape_project.tool.components;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.scape_project.tool.components package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Components_QNAME = new QName("http://scape-project.eu/component", "components");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.scape_project.tool.components
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link License }
     * 
     */
    public License createLicense() {
        return new License();
    }

    /**
     * Create an instance of {@link Measure }
     * 
     */
    public Measure createMeasure() {
        return new Measure();
    }

    /**
     * Create an instance of {@link QAObjectComparison }
     * 
     */
    public QAObjectComparison createQAObjectComparison() {
        return new QAObjectComparison();
    }

    /**
     * Create an instance of {@link MigrationAction }
     * 
     */
    public MigrationAction createMigrationAction() {
        return new MigrationAction();
    }

    /**
     * Create an instance of {@link Components }
     * 
     */
    public Components createComponents() {
        return new Components();
    }

    /**
     * Create an instance of {@link MigrationPath }
     * 
     */
    public MigrationPath createMigrationPath() {
        return new MigrationPath();
    }

    /**
     * Create an instance of {@link AcceptedMimetype }
     * 
     */
    public AcceptedMimetype createAcceptedMimetype() {
        return new AcceptedMimetype();
    }

    /**
     * Create an instance of {@link Characterisation }
     * 
     */
    public Characterisation createCharacterisation() {
        return new Characterisation();
    }

    /**
     * Create an instance of {@link QAPropertyComparison }
     * 
     */
    public QAPropertyComparison createQAPropertyComparison() {
        return new QAPropertyComparison();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Components }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://scape-project.eu/component", name = "components")
    public JAXBElement<Components> createComponents(Components value) {
        return new JAXBElement<Components>(_Components_QNAME, Components.class, null, value);
    }

}
