//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.23 at 04:39:20 PM WEST 
//


package eu.scape_project.tool.toolwrapper.data.tool_spec;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Declares an operating system dependency.
 * 
 * <p>Java class for OperatingSystemDependency complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OperatingSystemDependency">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="packageManager" type="{http://scape-project.eu/tool}PackageManager" maxOccurs="unbounded"/>
 *         &lt;element name="dependency" type="{http://scape-project.eu/tool}Dependency" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="operatingSystemName" use="required" type="{http://scape-project.eu/tool}OperatingSystemName" />
 *       &lt;attribute name="otherOperatingSystemName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="operatingSystemVersion" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OperatingSystemDependency", propOrder = {
    "packageManager",
    "dependency"
})
public class OperatingSystemDependency {

    @XmlElement(required = true)
    protected List<PackageManager> packageManager;
    protected List<Dependency> dependency;
    @XmlAttribute(required = true)
    protected OperatingSystemName operatingSystemName;
    @XmlAttribute
    protected String otherOperatingSystemName;
    @XmlAttribute
    protected String operatingSystemVersion;

    /**
     * Gets the value of the packageManager property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the packageManager property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPackageManager().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PackageManager }
     * 
     * 
     */
    public List<PackageManager> getPackageManager() {
        if (packageManager == null) {
            packageManager = new ArrayList<PackageManager>();
        }
        return this.packageManager;
    }

    /**
     * Gets the value of the dependency property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dependency property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDependency().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Dependency }
     * 
     * 
     */
    public List<Dependency> getDependency() {
        if (dependency == null) {
            dependency = new ArrayList<Dependency>();
        }
        return this.dependency;
    }

    /**
     * Gets the value of the operatingSystemName property.
     * 
     * @return
     *     possible object is
     *     {@link OperatingSystemName }
     *     
     */
    public OperatingSystemName getOperatingSystemName() {
        return operatingSystemName;
    }

    /**
     * Sets the value of the operatingSystemName property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperatingSystemName }
     *     
     */
    public void setOperatingSystemName(OperatingSystemName value) {
        this.operatingSystemName = value;
    }

    /**
     * Gets the value of the otherOperatingSystemName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherOperatingSystemName() {
        return otherOperatingSystemName;
    }

    /**
     * Sets the value of the otherOperatingSystemName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherOperatingSystemName(String value) {
        this.otherOperatingSystemName = value;
    }

    /**
     * Gets the value of the operatingSystemVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperatingSystemVersion() {
        return operatingSystemVersion;
    }

    /**
     * Sets the value of the operatingSystemVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperatingSystemVersion(String value) {
        this.operatingSystemVersion = value;
    }

}
