//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.27 at 03:47:31 PM WET 
//


package eu.scape_project.tool.toolwrapper.data.components_spec;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LicenseNameVersion.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LicenseNameVersion">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AFL-3.0"/>
 *     &lt;enumeration value="AGPL-3.0"/>
 *     &lt;enumeration value="APL-1.0"/>
 *     &lt;enumeration value="Apache-2.0"/>
 *     &lt;enumeration value="APSL-2.0"/>
 *     &lt;enumeration value="Artistic-2.0"/>
 *     &lt;enumeration value="AAL"/>
 *     &lt;enumeration value="BSL-1.0"/>
 *     &lt;enumeration value="CATOSL-1.1"/>
 *     &lt;enumeration value="CDDL-1.0"/>
 *     &lt;enumeration value="CPAL-1.0"/>
 *     &lt;enumeration value="CUA-OPL-1.0"/>
 *     &lt;enumeration value="EUDatagrid"/>
 *     &lt;enumeration value="EPL-1.0"/>
 *     &lt;enumeration value="ECL-2.0"/>
 *     &lt;enumeration value="EFL-2.0"/>
 *     &lt;enumeration value="Entessa"/>
 *     &lt;enumeration value="EUPL-1.1"/>
 *     &lt;enumeration value="Fair"/>
 *     &lt;enumeration value="Frameworx-1.0"/>
 *     &lt;enumeration value="AGPL-3.0"/>
 *     &lt;enumeration value="GPL-2.0"/>
 *     &lt;enumeration value="GPL-3.0"/>
 *     &lt;enumeration value="LGPL-2.1"/>
 *     &lt;enumeration value="LGPL-3.0"/>
 *     &lt;enumeration value="HPND"/>
 *     &lt;enumeration value="IPL-1.0"/>
 *     &lt;enumeration value="IPA"/>
 *     &lt;enumeration value="ISC"/>
 *     &lt;enumeration value="LPPL-1.3c"/>
 *     &lt;enumeration value="LPL-1.02"/>
 *     &lt;enumeration value="MirOS"/>
 *     &lt;enumeration value="MS-PL"/>
 *     &lt;enumeration value="MS-RL"/>
 *     &lt;enumeration value="MIT"/>
 *     &lt;enumeration value="Motosoto"/>
 *     &lt;enumeration value="MPL-2.0"/>
 *     &lt;enumeration value="Multics"/>
 *     &lt;enumeration value="NASA-1.3"/>
 *     &lt;enumeration value="NTP"/>
 *     &lt;enumeration value="Naumen"/>
 *     &lt;enumeration value="NGPL"/>
 *     &lt;enumeration value="Nokia"/>
 *     &lt;enumeration value="NPOSL-3.0"/>
 *     &lt;enumeration value="OCLC-2.0"/>
 *     &lt;enumeration value="OFL-1.1"/>
 *     &lt;enumeration value="OGTSL"/>
 *     &lt;enumeration value="OSL-3.0"/>
 *     &lt;enumeration value="PHP-3.0"/>
 *     &lt;enumeration value="PostgreSQL"/>
 *     &lt;enumeration value="Python-2.0"/>
 *     &lt;enumeration value="CNRI-Python"/>
 *     &lt;enumeration value="QPL-1.0"/>
 *     &lt;enumeration value="RPSL-1.0"/>
 *     &lt;enumeration value="RPL-1.5"/>
 *     &lt;enumeration value="RSCPL"/>
 *     &lt;enumeration value="SimPL-2.0"/>
 *     &lt;enumeration value="Sleepycat"/>
 *     &lt;enumeration value="SPL-1.0"/>
 *     &lt;enumeration value="Watcom-1.0"/>
 *     &lt;enumeration value="NCSA"/>
 *     &lt;enumeration value="VSL-1.0"/>
 *     &lt;enumeration value="W3C"/>
 *     &lt;enumeration value="WXwindows"/>
 *     &lt;enumeration value="Xnet"/>
 *     &lt;enumeration value="ZPL-2.0"/>
 *     &lt;enumeration value="Zlib"/>
 *     &lt;enumeration value="Other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "LicenseNameVersion")
@XmlEnum
public enum LicenseNameVersion {

    @XmlEnumValue("AFL-3.0")
    AFL_3_0("AFL-3.0"),
    @XmlEnumValue("AGPL-3.0")
    AGPL_3_0("AGPL-3.0"),
    @XmlEnumValue("APL-1.0")
    APL_1_0("APL-1.0"),
    @XmlEnumValue("Apache-2.0")
    APACHE_2_0("Apache-2.0"),
    @XmlEnumValue("APSL-2.0")
    APSL_2_0("APSL-2.0"),
    @XmlEnumValue("Artistic-2.0")
    ARTISTIC_2_0("Artistic-2.0"),
    AAL("AAL"),
    @XmlEnumValue("BSL-1.0")
    BSL_1_0("BSL-1.0"),
    @XmlEnumValue("CATOSL-1.1")
    CATOSL_1_1("CATOSL-1.1"),
    @XmlEnumValue("CDDL-1.0")
    CDDL_1_0("CDDL-1.0"),
    @XmlEnumValue("CPAL-1.0")
    CPAL_1_0("CPAL-1.0"),
    @XmlEnumValue("CUA-OPL-1.0")
    CUA_OPL_1_0("CUA-OPL-1.0"),
    @XmlEnumValue("EUDatagrid")
    EU_DATAGRID("EUDatagrid"),
    @XmlEnumValue("EPL-1.0")
    EPL_1_0("EPL-1.0"),
    @XmlEnumValue("ECL-2.0")
    ECL_2_0("ECL-2.0"),
    @XmlEnumValue("EFL-2.0")
    EFL_2_0("EFL-2.0"),
    @XmlEnumValue("Entessa")
    ENTESSA("Entessa"),
    @XmlEnumValue("EUPL-1.1")
    EUPL_1_1("EUPL-1.1"),
    @XmlEnumValue("Fair")
    FAIR("Fair"),
    @XmlEnumValue("Frameworx-1.0")
    FRAMEWORX_1_0("Frameworx-1.0"),
    @XmlEnumValue("GPL-2.0")
    GPL_2_0("GPL-2.0"),
    @XmlEnumValue("GPL-3.0")
    GPL_3_0("GPL-3.0"),
    @XmlEnumValue("LGPL-2.1")
    LGPL_2_1("LGPL-2.1"),
    @XmlEnumValue("LGPL-3.0")
    LGPL_3_0("LGPL-3.0"),
    HPND("HPND"),
    @XmlEnumValue("IPL-1.0")
    IPL_1_0("IPL-1.0"),
    IPA("IPA"),
    ISC("ISC"),
    @XmlEnumValue("LPPL-1.3c")
    LPPL_1_3_C("LPPL-1.3c"),
    @XmlEnumValue("LPL-1.02")
    LPL_1_02("LPL-1.02"),
    @XmlEnumValue("MirOS")
    MIR_OS("MirOS"),
    @XmlEnumValue("MS-PL")
    MS_PL("MS-PL"),
    @XmlEnumValue("MS-RL")
    MS_RL("MS-RL"),
    MIT("MIT"),
    @XmlEnumValue("Motosoto")
    MOTOSOTO("Motosoto"),
    @XmlEnumValue("MPL-2.0")
    MPL_2_0("MPL-2.0"),
    @XmlEnumValue("Multics")
    MULTICS("Multics"),
    @XmlEnumValue("NASA-1.3")
    NASA_1_3("NASA-1.3"),
    NTP("NTP"),
    @XmlEnumValue("Naumen")
    NAUMEN("Naumen"),
    NGPL("NGPL"),
    @XmlEnumValue("Nokia")
    NOKIA("Nokia"),
    @XmlEnumValue("NPOSL-3.0")
    NPOSL_3_0("NPOSL-3.0"),
    @XmlEnumValue("OCLC-2.0")
    OCLC_2_0("OCLC-2.0"),
    @XmlEnumValue("OFL-1.1")
    OFL_1_1("OFL-1.1"),
    OGTSL("OGTSL"),
    @XmlEnumValue("OSL-3.0")
    OSL_3_0("OSL-3.0"),
    @XmlEnumValue("PHP-3.0")
    PHP_3_0("PHP-3.0"),
    @XmlEnumValue("PostgreSQL")
    POSTGRE_SQL("PostgreSQL"),
    @XmlEnumValue("Python-2.0")
    PYTHON_2_0("Python-2.0"),
    @XmlEnumValue("CNRI-Python")
    CNRI_PYTHON("CNRI-Python"),
    @XmlEnumValue("QPL-1.0")
    QPL_1_0("QPL-1.0"),
    @XmlEnumValue("RPSL-1.0")
    RPSL_1_0("RPSL-1.0"),
    @XmlEnumValue("RPL-1.5")
    RPL_1_5("RPL-1.5"),
    RSCPL("RSCPL"),
    @XmlEnumValue("SimPL-2.0")
    SIM_PL_2_0("SimPL-2.0"),
    @XmlEnumValue("Sleepycat")
    SLEEPYCAT("Sleepycat"),
    @XmlEnumValue("SPL-1.0")
    SPL_1_0("SPL-1.0"),
    @XmlEnumValue("Watcom-1.0")
    WATCOM_1_0("Watcom-1.0"),
    NCSA("NCSA"),
    @XmlEnumValue("VSL-1.0")
    VSL_1_0("VSL-1.0"),
    @XmlEnumValue("W3C")
    W_3_C("W3C"),
    @XmlEnumValue("WXwindows")
    W_XWINDOWS("WXwindows"),
    @XmlEnumValue("Xnet")
    XNET("Xnet"),
    @XmlEnumValue("ZPL-2.0")
    ZPL_2_0("ZPL-2.0"),
    @XmlEnumValue("Zlib")
    ZLIB("Zlib"),
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    LicenseNameVersion(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LicenseNameVersion fromValue(String v) {
        for (LicenseNameVersion c: LicenseNameVersion.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
