//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.27 at 03:47:31 PM WET 
//


package eu.scape_project.tool.toolwrapper.data.components_spec;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MigrationAction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MigrationAction">
 *   &lt;complexContent>
 *     &lt;extension base="{http://scape-project.eu/component}Component">
 *       &lt;sequence>
 *         &lt;element name="migrationPath" type="{http://scape-project.eu/component}MigrationPath" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="profile" use="required" type="{http://scape-project.eu/component}MigrationProfile" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MigrationAction", propOrder = {
    "migrationPath"
})
public class MigrationAction
    extends Component
{

    @XmlElement(required = true)
    protected List<MigrationPath> migrationPath;
    @XmlAttribute(required = true)
    protected String profile;

    /**
     * Gets the value of the migrationPath property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the migrationPath property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMigrationPath().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MigrationPath }
     * 
     * 
     */
    public List<MigrationPath> getMigrationPath() {
        if (migrationPath == null) {
            migrationPath = new ArrayList<MigrationPath>();
        }
        return this.migrationPath;
    }

    /**
     * Gets the value of the profile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfile() {
        return profile;
    }

    /**
     * Sets the value of the profile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfile(String value) {
        this.profile = value;
    }

}
