//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.27 at 03:47:31 PM WET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://scape-project.eu/component", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package eu.scape_project.tool.toolwrapper.data.components_spec;
