//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.06 at 06:14:07 PM WET 
//


package eu.scape_project.tool.toolwrapper.data.components_spec;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TypeOfProcessingInstruction.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TypeOfProcessingInstruction">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="JAVA"/>
 *     &lt;enumeration value="BASH"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TypeOfProcessingInstruction")
@XmlEnum
public enum TypeOfProcessingInstruction {

    JAVA,
    BASH;

    public String value() {
        return name();
    }

    public static TypeOfProcessingInstruction fromValue(String v) {
        return valueOf(v);
    }

}
